# Data Manipulation using tidyr

In [15]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [21]:
## Long to Wide with pivot_wider

Learning Objectives

Understand the concept of a wide and a long table format and for which purpose those formats are useful.
Understand what key-value pairs are.
Reshape a data frame from long to wide format and back with the pivot_wider and pivot_longer commands from the tidyr package.
Export a data frame to a .csv file.

See: https://cengel.github.io/R-data-wrangling/tidyr.html

In [17]:
# We will be working a small subset of the data from the Stanford Open Policing Project. 
# It contains information about traffic stops in the state of Mississippi during January 2013 to mid-July of 2016
stops <- read_csv("../data/MS_trafficstops_bw_age.csv", show_col_types = FALSE)
head(stops)

  id            stop_date  county_name county_fips police_department
1 MS-2013-00001 2013-01-01 Jones       28067       Mississippi Highway Patrol
2 MS-2013-00002 2013-01-01 Lauderdale  28075       Mississippi Highway Patrol
3 MS-2013-00003 2013-01-01 Pike        28113       Mississippi Highway Patrol
4 MS-2013-00004 2013-01-01 Hancock     28045       Mississippi Highway Patrol
5 MS-2013-00005 2013-01-01 Holmes      28051       Mississippi Highway Patrol
6 MS-2013-00006 2013-01-01 Jackson     28059       Mississippi Highway Patrol
  driver_gender driver_birthdate driver_race officer_id driver_age
1 male          1950-06-14       Black       J042       63
2 male          1967-04-06       Black       B026       46
3 male          1974-04-15       Black       M009       39
4 male          1981-03-23       White       K035       32
5 male          1992-08-03       White       D028       20
6 female        1960-05-02       White       K023       53
  violation
1 Seat belt
2 Careless driving
3 Speeding
4 Speeding
5 Speeding
6 Speeding

# Long to Wide with pivot_wider

Now let’s see this in action. First, using dplyr, let’s create a data frame with the counts of different violations for each county

In [19]:
violations <- stops %>%
  count(county_name, violation, name = "n_violations")

violations

    county_name violation                n_violations
1   Adams       Breaks-Lights-etc           7
2   Adams       Careless driving           48
3   Adams       License-Permit-Insurance  118
4   Adams       Other or unknown           35
5   Adams       Seat belt                 229
6   Adams       Speeding                  505
7   Alcorn      Breaks-Lights-etc          62
8   Alcorn      Careless driving          100
9   Alcorn      License-Permit-Insurance  737
10  Alcorn      Other or unknown          418
11  Alcorn      Seat belt                 629
12  Alcorn      Speeding                 1399
13  Amite       Breaks-Lights-etc          47
14  Amite       Careless driving           86
15  Amite       License-Permit-Insurance  370
16  Amite       Other or unknown          143
17  Amite       Seat belt                 336
18  Amite       Speeding                 1939
19  Attala      Breaks-Lights-etc          99
20  Attala      Careless driving          113
21  Attala      License-Permit-Insurance  526
22  Attala      Other or unknown          155
23  Attala      Seat belt                 748
24  Attala      Speeding                 2562
25  Benton      Breaks-Lights-etc           3
26  Benton      Careless driving            9
27  Benton      License-Permit-Insurance   73
28  Benton      Other or unknown           26
29  Benton      Seat belt                  29
30  Benton      Speeding                   74
⋮   ⋮           ⋮                        ⋮
458 Wayne       Seat belt                 461
459 Wayne       Speeding                 3041
460 Webster     Breaks-Lights-etc           1
461 Webster     License-Permit-Insurance   14
462 Webster     Other or unknown            1
463 Webster     Seat belt                  10
464 Webster     Speeding                  130
465 Wilkinson   Breaks-Lights-etc           1
466 Wilkinson   License-Permit-Insurance   16
467 Wilkinson   Other or unknown            6
468 Wilkinson   Seat belt                   5
469 Wilkinson   Speeding                   15
470 Winston     Breaks-Lights-etc          27
471 Winston     Careless driving           85
472 Winston     License-Permit-Insurance  696
473 Winston     Other or unknown          290
474 Winston     Seat belt                 294
475 Winston     Speeding                 2930
476 Yalobusha   Breaks-Lights-etc           3
477 Yalobusha   Careless driving           13
478 Yalobusha   License-Permit-Insurance   48
479 Yalobusha   Other or unknown           25
480 Yalobusha   Seat belt                 125
481 Yalobusha   Speeding                  108
482 Yazoo       Breaks-Lights-etc          28
483 Yazoo       Careless driving           86
484 Yazoo       License-Permit-Insurance  239
485 Yazoo       Other or unknown          105
486 Yazoo       Seat belt                 202
487 Yazoo       Speeding                 2868

Now, to make this long data wide, we use pivot_wider from tidyr to turn the different violation types into columns, where each possible value of the violation variable receives its own column.

pivot_wider() takes three principal arguments:

1. the data
2. the names_from column variable whose values will become new column names.
3. the values_from column variable whose values will fill the new column cells.

We’ll use a pipe into pivot_wider so we can leave out the data argument

In [25]:
violations_wide <- violations %>%
  pivot_wider(names_from = violation, 
              values_from = n_violations) 

head(violations_wide)

  county_name Breaks-Lights-etc Careless driving License-Permit-Insurance
1 Adams        7                 48               118
2 Alcorn      62                100               737
3 Amite       47                 86               370
4 Attala      99                113               526
5 Benton       3                  9                73
6 Bolivar     57                139              1034
  Other or unknown Seat belt Speeding
1  35              229        505
2 418              629       1399
3 143              336       1939
4 155              748       2562
5  26               29         74
6 254              729       2313

# Wide to long with pivot_longer

What if we had the opposite problem, and wanted to go from a wide to long format? For that, we use pivot_longer, which will increase the number of rows and decrease the number of columns.

We are gathering the multiple violation columns and turn them into a pair of new variables. One variable includes the column names as values, and the other variable contains the values in each cell previously associated with the column names.

pivot_longer() takes four principal arguments:

1. the data
2. cols are the names of the columns we use to fill the a new values variable (or to drop).
3. the names_to a string specifying the name of the column to create from the data stored in the column names (cols)
4. the values_to which is also a string, specifying the name of the column to create from the data stored in cell values.
So, to go backwards from violations_wide, and exclude county_name from the long format, we would do the following:

In [33]:
violations_long <- violations_wide %>%
  pivot_longer(cols = -county_name,        # exclude column with county name
               names_to = "violation",     # name is a string!
               values_to = "n_violations")            # also a string

head(violations_long)

  county_name violation                n_violations
1 Adams       Breaks-Lights-etc          7
2 Adams       Careless driving          48
3 Adams       License-Permit-Insurance 118
4 Adams       Other or unknown          35
5 Adams       Seat belt                229
6 Adams       Speeding                 505

See: https://tavareshugo.github.io/r-intro-tidyverse-gapminder/09-reshaping/index.html